"""initial migration

Revision ID: 35cc0e8472dd
Revises: 
Create Date: 2021-10-01 11:29:08.619057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35cc0e8472dd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("current_login_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_ip", sa.String(length=100), nullable=True),
        sa.Column("current_login_ip", sa.String(length=100), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "odk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("password_encrypt", sa.LargeBinary(), nullable=True),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "odm",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("password_encrypt", sa.LargeBinary(), nullable=True),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "odkproject",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("odk_id", sa.Integer(), nullable=False),
        sa.Column("remote_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["odk_id"],
            ["odk.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "odmproject",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("odm_id", sa.Integer(), nullable=False),
        sa.Column("remote_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["odm_id"],
            ["odm.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mesh",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("odmproject_id", sa.Integer(), nullable=True),
        sa.Column("odkproject_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW", "READY", "PROCESSING", "FINISHED", "ERROR", name="meshstatus"
            ),
            nullable=True,
        ),
        sa.Column("current_task", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["odkproject_id"],
            ["odkproject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["odmproject_id"],
            ["odmproject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mesh_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("zipfile", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mesh_id"],
            ["mesh.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game")
    op.drop_table("mesh")
    op.drop_table("odmproject")
    op.drop_table("odkproject")
    op.drop_table("roles_users")
    op.drop_table("odm")
    op.drop_table("odk")
    op.drop_table("user")
    op.drop_table("role")
    # ### end Alembic commands ###
